server:
  port: 8089
spring:
  application:
#    name: feginserver
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///1703e?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  resources:
    static-locations: file:${file.path}
  servlet:
    multipart:
      max-file-size: 10240000
      max-request-size: 10240000
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
eureka:
  client:
    fetch-registry: true   #从注册中心拉出注册列表
    service-url:
      defaultZone: http://localhost:1010/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file: e:/logs/good-springboot.log
  level:
    com.jinqian.mapper: debug

file:
  domain: http://127.0.0.1:8089/
  path: e:/pic/


