server:
  port: 10001
  #servlet:
  #  context-path: /apollo/
spring:
  application:
    name: gatewayserver
    #getaway
  cloud:
    gateway:
      routes:
        - id : jpaserver
          uri: lb://jpaserver
          order: 0
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

eureka:
  client:
    fetch-registry: true   #从注册中心拉出注册列表
    service-url:
      defaultZone: http://localhost:1010/eureka

